---
name: GainXPV2
version: 1.1.0
main: Julicraft_44\GainXPV2\Main
api: 3.0.0

commands:
    xp:
        description: gain or remove xp from a spezific player
        permission: gainxp.use
        
permissions:
    gainxp.use:
        description: xp permission
        default: op
...
