---
command-usage: "Usage: /xp <add:remove> <Player> <Amount>"

no-perm: "You do not have the permission to run this command"

no-found: "This player cannot be found or isn't online"

to-high-amount: "The amount of %amount xp is too high. Only %current xp levels are avalable"

succsess-sender-add: "You added %amount xp to a player"

succsess-target-add: "You gain %amount xp from a player"

succsess-sender-rem: "You removed %amount xp from a player"

succsess-target-rem: "You lose %amount xp"
...

