---
command-usage: "Usage: /xp <add:remove> <Player> <Amount>"

no-perm: "You do not have the permission to run this command"

to-high-amount: "The amount of {amount}xp is too high. Player {taget} has only {current}xp levels"

succsess-sender-add: "You added {amount}xp to {target}"

succsess-target-add: "You gain {amount}xp from {sender}"

succsess-sender-rem: "You removed {amount}xp from {target}"

succsess-target-rem: "You lose {amount}xp from {sender}"
...

